### ISSUE TITLE
Accessibility Problems

### ISSUE THREAD

**Issue by mgifford** [pages-themes/minimal#10]
There are some accessibility problems with this theme.

1) the language of the page should be provided.
2) there are color contrast issues

Maybe this should be reported here though https://github.com/orderedlist/minimal

Not sure.

**Comment by benbalter** [comment]
> there are color contrast issues

Can you be more specific?

> the language of the page should be provided.
 
Can you be more specific? As a dedicated meta tag? As a property on the HTML element? In a human readable way? Someplace else?

**Comment by benbalter** [comment]
> I don't know how to add the language of the page given that it may not be English, but:

http://webaim.org/standards/wcag/checklist#sc3.1.1

Gotcha. That was my question. Thanks for teaching a :man: to :fish:. Will get a PR going right now. Simple enough to implement. It sounds like we should do this across all our themes?

**Comment by mgifford** [comment]
I've only tested these two, but yes..  Having this across the board will help.

Particularly as governments start using Pages I do think it will be useful to have the templates follow solid accessibility practices.

**Comment by benbalter** [comment]
> I've only tested these two, but yes.. Having this across the board will help.

I have a script and will make the change across all the theme repos right now.

**Comment by mgifford** [comment]
That's great.  

Some links on focus (and hover):
http://www.washington.edu/accessibility/checklist/focus/
https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/

Keyboard accessibility is often forgotten as it isn't easily caught by automated tools.

**Comment by benbalter** [comment]
> Thanks. I have a script and will make the change across all the theme repos right now.

Fixed via https://github.com/pages-themes/minimal/commit/2246632561e692e380cd60c3aaa9ae47092453c4 and similar commits to all the Pages themes. Thanks for the heads up! :smile:

**Comment by mgifford** [comment]
Hey, that's amazing..  Like I tell folks, it is always worth looking to the source of the problem.  Getting these templates fixed here will end up benefiting millions of web pages over time.  

Thanks for pushing these changes through (across the board) and doing so in a way that makes for a very compelling story about open-source approaches to addressing accessibility problems.
