### ISSUE TITLE
Icon adding guide needed

### ISSUE THREAD

**Issue by coder-lg** [pages-themes/minimal#102]
I wanna add an icon to my site, but it doesn't accept it. I got a 32x32 image on Github, and theme is minimal. But, my site is in Cayman right now and the icon is making it crash. Can you tell how to solve this error? Must I use an ico file?

**Comment by coder-lg** [comment]
Also, the image size is 50x65

**Comment by parkr** [comment]
You can set a favicon by copying `_includes/head-custom.html` from this repo to your site (at the same path in your site) then customizing. Here is the Mozilla Developer Network documentation on favicon, which includes information about formats: https://developer.mozilla.org/en-US/docs/Glossary/Favicon

**Comment by coder-lg** [comment]
Already solved, but thanks for the suggestion, I will try it :)
