### ISSUE TITLE
required_ruby_version in gemspec

### ISSUE THREAD

**Issue by innawy** [pages-themes/minimal#105]
Hi! I came across the below offense during the build process of script/cibuild. I'm not sure how to fix this.

```
Offenses:

jekyll-theme-minimal.gemspec:1:1: C: Gemspec/RequiredRubyVersion: required_ruby_version should be specified.
# frozen_string_literal: true
^

3 files inspected, 1 offense detected
Error: Process completed with exit code 1.
```

I have tried adding the line below in jekyll-theme-minimal.gemspec, however which required ruby version should I be using?
`s.required_ruby_version       = '2.4.0'`

Thank you!

**Comment by parkr** [comment]
Hello! I have resolved this on the `master` branch. Thanks!
