### ISSUE TITLE
Adjusting Width of page

### ISSUE THREAD

**Issue by johnodonnell123** [pages-themes/minimal#107]
How do I adjust the total width of the page, removing some of the buffer/whitespace on each side? 

![Example Image](https://user-images.githubusercontent.com/59580420/115085039-641d6900-9ecf-11eb-9977-4b0b758dcaea.PNG)

**Comment by uyencfi** [comment]
Did you find a way to do this? Thanks.

**Comment by johnodonnell123** [comment]
I did, thank you

John ODonnell
936-537-0533

**Comment by uyencfi** [comment]
@johnodonnell123 I'm having this problem too. Can you show me how you did it? Thank you!

**Comment by BDHU** [comment]
Beware @johnodonnell123 's solution might fix the width issue but when the browser window is narrower contents in the right column may overlap with the sidebar. If that's not a problem just play with the width elements in the [jekyll-theme-minimal.scss](https://github.com/pages-themes/minimal/blob/master/_sass/jekyll-theme-minimal.scss) file.

![demo](https://user-images.githubusercontent.com/9762261/133510931-8e133287-8b1f-4dfb-8b23-acc47af117f8.png)
