### ISSUE TITLE
How do I specify the address of home page md file?

### ISSUE THREAD

**Issue by MuhammadWasif** [pages-themes/minimal#108]
I am deploying through GitHub Pages. In main branch, I have `docs` folder. It's deploying the website through doc folder. But I have to copy the `README.md` from root to `/docs`.
Can I specify the home page of website in yml file?
`home-page: ../README.md` something like this?
because currently it is taking `index.md` of the folder (that has `_config.yml`) as home page. How can I change this?

**Comment by parkr** [comment]
Hi, unfortunately if you set your Pages source to `/docs`, then your entire site must be in that directory. You can write in to support@github.com to suggest this feature, but in general you need to have the whole site in one place.
