### ISSUE TITLE
Changes to /assets/css/style.scss not affecting page

### ISSUE THREAD

**Issue by YakobovLior** [pages-themes/minimal#110]
Hello,

I'm trying to override the widths of both **wrapper** and **section** tags, and my **style.scss** file looks like this:
```
---
---

@import "{{ site.theme }}";

wrapper {
  width: 1060px;
}

section {
  width: 700px;
}
```

For some reason I can't make the changes affect, and thus increasing the widths of the page.
What am I missing, do I have some configuration issue here?

Thanks,
Lior

**Comment by YakobovLior** [comment]
I figured out now that since I configured root folder for page under **docs**, I had to put **assets** folder inside **docs** folder to make it work.

**Comment by JacobBumgarner** [comment]
This still isn't affecting my page unfortunately.  I'm building from root rather than /docs/ but can't get implement any alterations made by my styles.scss file.
