### ISSUE TITLE
The homepage not change

### ISSUE THREAD

**Issue by zhangxinyu-xyz** [pages-themes/minimal#111]
Hi developers,

I modified the _site/index.html and index.md by myself. I run "bundle exec jekyll serve" to start the preview server and it looks good. However, when I git push these changes, the homepage is not changed. Do you know how can I solve it?

**Comment by BDHU** [comment]
Github page takes a while to build. Did you see any changes after some time? Or did you receive any error messages during building?

**Comment by zhangxinyu-xyz** [comment]
> Github page takes a while to build. Did you see any changes after some time? Or did you receive any error messages during building?

Thanks. I have fixed it.
