### ISSUE TITLE
issue with scss file -- import not found or unreadable: minimal

### ISSUE THREAD

**Issue by dpuelz** [pages-themes/minimal#115]
hey folks, I'm getting the following error:

Your SCSS file `assets/css/style.scss` has an error on line 12: File to import not found or unreadable: minimal. Load path: /tmp/jekyll-remote-theme-20210723-6-pise0o/_sass. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.

The only thing I did was update an unrelated link on my webpage.  Do you know what's going on?  Does it have something to do with the minimal remote theme?  my site is here:

https://github.com/dpuelz/dpuelz.github.io

thanks!

**Comment by dpuelz** [comment]
here is the updated error:

Your SCSS file `assets/css/style.scss` has an error on line 1: File to import not found or unreadable: minimal. Load path: /tmp/jekyll-remote-theme-20210723-7-1lrxn5f/_sass. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss

there appears to be something wrong when calling site.theme.

**Comment by pcunning** [comment]
I'm seeing this issue as well.

**Comment by wainwrighth** [comment]
Adding that I'm seeing it for visibility. Also switched to the cayman jekyll remote theme to see if the issue persisted and it failed with the same error

**Comment by AnonyPla** [comment]
See maybe https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882

**Comment by dpuelz** [comment]
hard coding *jekyll-theme-minimal* in the scss file fixed the issue, but it's kind of a workaround.  Here's the new beginning of the file.

---
---

@import 'jekyll-theme-minimal';

**Comment by parkr** [comment]
#118 added a file called `minimal.scss`. Feel free to update your `_config.yml`:

```diff
- theme: jekyll-theme-minimal
+ remote_theme: pages-themes/minimal@master
```

**Comment by AnonyPla** [comment]
https://github.com/pages-themes/cayman/issues/131#issuecomment-886092689

**Comment by parkr** [comment]
Hello! This should now be fixed in v217 of the `github-pages` gem!
