### ISSUE TITLE
The instruction to preview on a local computer doesn't work

### ISSUE THREAD

**Issue by kmyk** [pages-themes/minimal#116]
For a local preview, the Usage section of README.md says to use `theme: jekyll-theme-minimal` and `gem "github-pages", group: :jekyll_plugins`. However, this doesn't work with an error `jekyll 3.9.0 | Error:  The jekyll-theme-minimal theme could not be found.`. This seems to be caused by `pages-gem`'s pull request https://github.com/github/pages-gem/pull/772.

**Comment by AnonyPla** [comment]
See https://github.com/pages-themes/cayman/issues/130#issuecomment-886056882
