### ISSUE TITLE
GitHub Pages issues: Unable use /xxx.md View themed Markdown

### ISSUE THREAD

**Issue by Dobby233Liu** [pages-themes/minimal#12]
A ****Example**** : [404.md](https://dobby233liu.github.io/404.md)

**Comment by Dobby233Liu** [comment]
A images
![screenshot_2017-05-19-18-43-51](https://cloud.githubusercontent.com/assets/28653235/26244695/6b441916-3c56-11e7-8029-dbd55c409db8.png)

**Comment by benbalter** [comment]
https://dobby233liu.github.io/404.html renders for me as expected.
