### ISSUE TITLE
Page title in default layout

### ISSUE THREAD

**Issue by Jmuccigr** [pages-themes/minimal#13]
The page title seems a bit long with the combination of the site title and its author (which requires github btw). Would it make sense to shorten it by eliminating the author info? This would leave it:

<title>{{ site.title | default: site.github.repository_name }}</title>

**Comment by benbalter** [comment]
@Jmuccigr the title is set by https://github.com/jekyll/jekyll-seo-tag. If you'd like to modify the title, it'd be best to submit a pull request upstream.

**Comment by Jmuccigr** [comment]
@benbalter Thanks for the suggestion. I've taken a look, but it's not clear to me where this is set over in the other project. Could you lend me another assist? TIA.

**Comment by benbalter** [comment]
https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag/drop.rb#L43-L54
