### ISSUE TITLE
post layout?

### ISSUE THREAD

**Issue by Jmuccigr** [pages-themes/minimal#14]
Any reason for the lack of post layout?

I've just started to use the theme (thanks!) and for posts have removed the title above the content, and put the page title in the header (which I've added to the _config.yml).

**Comment by benbalter** [comment]
Minimal was intended as a minimal Jekyll theme, and as such, doesn't have support for Posts out of the box, only Pages.

**Comment by Jmuccigr** [comment]
I was thinking more of minimal in the sense of the style, rather than the support of different kinds of documents.

So no interest in taking PRs then?

**Comment by benbalter** [comment]
@Jmuccigr Please, if you're interested, I'd be happy to review a PR.

**Comment by Jmuccigr** [comment]
Let me dig it up. :-)

**Comment by Jmuccigr** [comment]
OK, finally did this: #26.

**Comment by makrandgupta** [comment]
I believe now is a good time to close this issue

**Comment by Jmuccigr** [comment]
So it would seem.
