### ISSUE TITLE
Check to see whether page is an organization page

### ISSUE THREAD

**Issue by sbromberger** [pages-themes/minimal#16]
In https://github.com/pages-themes/minimal/blob/c827e10a73ef8c75e99b34923c38cc1273d40713/_layouts/default.html#L20-L26, the code checks to see whether the page is a user page or project page. However, organization pages should also be checked (and should minimally be treated like project pages).

**Comment by benbalter** [comment]
@sbromberger would you be interested in submitting a pull request with that functionality?

**Comment by sbromberger** [comment]
@benbalter I'd be able to do it later this week, probably. Just to confirm - is there a variable equivalent to `site.github.is_user_page` that applies to organizations? (I'm not even sure where these vars are coming from.)

**Comment by benbalter** [comment]
> I'm not even sure where these vars are coming from

See https://help.github.com/articles/repository-metadata-on-github-pages/. It may not be possible with the metadata currently exposed.

**Comment by pavelkryukov** [comment]
> It may not be possible with the metadata currently exposed.

Can we check the size of "organization_members" field? If it is 1, we use "View My GitHub Profile", "View Our GitHub Profile" otherwise.
