### ISSUE TITLE
Unable settin up theme

### ISSUE THREAD

**Issue by giacman** [pages-themes/minimal#21]
Hello, 

I'm trying to preview my site locally and eventually publish it on my github page.

I'm following documentation: I have added `theme: jekyll-theme-minimal` to my _config.yml file, and I have added `gem "github-pages", group: :jekyll_plugins` to my Gemfile. 

I am now able to run locally with `bundle exec jekyll serve` but the website still has the base Jekyll theme. Also I have merged on github and githubpage still shows the base Jekyll as well.

Not sure why, sorry for the simple question, I'm new to Ruby and Jekyll.

**Comment by benbalter** [comment]
@giacman We can't speak to the specifics of your local setup. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
