### ISSUE TITLE
Customisable wording for GitHub link

### ISSUE THREAD

**Issue by technige** [pages-themes/minimal#42]
For a user page, the GitHub link is behind the fixed wording "View My GitHub Profile". In our case, this wording (specifically the word "my") doesn't quite make sense as the profile is for an organisation, rather than a user.

Would it be possible to allow the wording to be customised for such links?

**Comment by ericytsang** [comment]
If you still want to change the wording:

1. create a file here `[project root]/_layouts/default.html`
2. copy the contents of [this repo's default.html](https://github.com/pages-themes/minimal/blob/master/_layouts/default.html) into it
3. now you'll have access to the html so you can modify the wording
