### ISSUE TITLE
How is date used?

### ISSUE THREAD

**Issue by hollowomnicron** [pages-themes/minimal#45]
On the Post layout, how do i add the date

**Comment by ClydeDz** [comment]
@hollowomnicron,

You would need to add a `date` variable to the header of the page that's using the post layout.

For instance, in this repo, this page uses the post layout. 
https://github.com/pages-themes/minimal/blob/master/another-page.md

So in the header of the page, you would edit the Front Matter to something like this -
```
---
layout: default
date: 2018-10-01
---
```


More about [Front Matter here](https://jekyllrb.com/docs/front-matter/).
