### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by cooperkong** [pages-themes/minimal#6]
Hi
I got this error when setting up github pages with this theme,
the email I got doesn't have any description related with the failure.
I just change the default theme to 'jekyll-theme-minimal', it builds fine when switch back to 'minima' theme.
Thanks.

**Comment by benbalter** [comment]
@cooperkong we're not able to provide individual support in this forum. Can you please [contact GitHub support](https://github.com/contact) who should be able to help get your issue resolved?
