### ISSUE TITLE
I made my website repository public to private and back to public and now its not loading

### ISSUE THREAD

**Issue by ajwadjaved** [pages-themes/minimal#61]
Repository https://github.com/ajwadjaved/ajwadjaved.github.io
Website ajwadjaved.github.io, its giving me a 404 now

**Comment by benbalter** [comment]
We can't speak to the specifics of your particular site. If you [contact GitHub support](https://github.com/contact) (or [post to the GitHub Community forum](https://github.community/)) they should be able to help you get things straightened out. 😸
