### ISSUE TITLE
Setting site.github.is_project_page

### ISSUE THREAD

**Issue by enryH** [pages-themes/minimal#65]
Is it possible to modify in the `_config.yml` or jekyll Front Matter the setting for `site.github.is_project_page` in order to modify the behaviour of the website-building in [`_layouts/defaut.html`](https://github.com/pages-themes/minimal/blob/master/_layouts/default.html)

I tried several combination, but did not get it to work. Thanks in advance!

**Comment by edouard-lopez** [comment]
see: https://github.com/pages-themes/cayman/issues/29#issuecomment-339016299
