### ISSUE TITLE
Please make themes GDPR compliant

### ISSUE THREAD

**Issue by geira** [pages-themes/minimal#67]
Really like these themes, but currently cannot use them as they contain Google Analytics tracking. According to [a ruling in the The Court of Justice of the European Union](https://piwik.pro/blog/cjeu-trackers-consent-requirements/) (CJEU) in November 2019, "analytics and tracking"[ is considered non-necessary cookies](https://adzerk.com/blog/gdpr-google-analytics/) and so requires opt-in consent from the user before setting any cookies. Would therefore like this feature to be configurable in site settings to [avoid breaking the law](https://www.blastanalytics.com/blog/gdpr-need-consent-for-google-analytics-tracking).

**Comment by geira** [comment]
It seems that this is already implemented, sorry for the confusion.
`{% if site.google_analytics %}`

**Comment by shoumikchow** [comment]
The opt-in consent bar doesn't actually show up.
