### ISSUE TITLE
include ToC in header

### ISSUE THREAD

**Issue by stangri** [pages-themes/minimal#7]
Thank you for a wonderful theme!

is there an easy way to include ToC inside the header (left side) of the layout? I was hoping I could enable it via a variable, but looking at https://github.com/pages-themes/minimal/blob/master/_layouts/default.html it doesn't seem possible without modifying the layout HTML which I'm very uncomfortable with.

Thanks!

**Comment by benbalter** [comment]
> it doesn't seem possible without modifying the layout HTML which I'm very uncomfortable with.

You can override the default layout by following [these instructions](https://github.com/pages-themes/minimal#layouts).

**Comment by stangri** [comment]
Well, overriding/modifying layout and learning how to auto-build ToC is what I wanted to avoid. ;)
Would it be outside of scope of this theme to auto-build ToC in the header?
