### ISSUE TITLE
Header and footer overlap with short and wide browser window

### ISSUE THREAD

**Issue by vipasu** [pages-themes/minimal#71]
Hi,

Just wanted to share that sometimes the header and footer can display on top of each other in a desktop browser. When the window becomes narrow enough, it switches to single column display. However, if you just make the window shorter, it keeps the 2 column format and the header and footer can overlap.

Best,
Vincent

**Comment by schlamar** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/238652/82117117-6da5ca80-976e-11ea-9ca5-9caf66887eaf.png)

**Comment by tildehacker** [comment]
I submitted a pull request (#76) that fixes this issue.

If you want to use this fix before it gets merged, replace:

```
theme: jekyll-theme-minimal
```

by

```
remote_theme: tildehacker/minimal@e0ea159aa5b010093640f661c8c8a05677540c0a
```

in your `_config.yml` file. `e0ea159aa5b010093640f661c8c8a05677540c0a` is a reference to the branch that contains the fix of this issue (I used `git show-ref | grep fix/overlapping-header-and-footer` to get the reference).
