### ISSUE TITLE
Using Multiple default.html pages?

### ISSUE THREAD

**Issue by RylanSchaeffer** [pages-themes/minimal#72]
This is probably a misuse of an issue, but I want to add custom links to the left side of the index Markdown page. I discovered that I can create a `_layouts/default.html` file, which works well. However, I'd also like to have different pairings of markdown files and default.html files. Is there a way to do this? Can I specify for a particular markdown file which corresponding default.html I want used?

**Comment by brasofilo** [comment]
If I'm getting you right, it would be a new layout: https://jekyllrb.com/docs/layouts/

Add your custom file `_layouts/mypage.html` and then on the markdown file, you'd have the header:

```
---
layout: mypage
---
```
