### ISSUE TITLE
How to add .png file into the logo section of the minimal theme of github pages?

### ISSUE THREAD

**Issue by SiddhanthNB** [pages-themes/minimal#81]

**Comment by SiddhanthNB** [comment]
While I was setting up Github pages using minimal themes, I was unable to add a picture to the logo part of the template. Can I how to add a picture there?

**Comment by redawl** [comment]
Add this line to the projects _config.yml:
logo: relativepathtopng

Example:
logo: cat.png

**Comment by SiddhanthNB** [comment]
Thank you.
