### ISSUE TITLE
Adding LaTeX support

### ISSUE THREAD

**Issue by jfparisi** [pages-themes/minimal#86]
Dear Minimal theme,

I would love to see LaTeX support for the theme; this would be extremely helpful for writing equations in text. I have attempted to write code in my own branch of minimal to implement MathJax, as per the instructions here: http://sgeos.github.io/github/jekyll/2016/08/21/adding_mathjax_to_a_jekyll_github_pages_blog.html

Unfortunately, my implementation was not successful; I am a GitHub novice, so that might be why it failed. It should only be a few lines of code.

Best wishes,

Jason

**Comment by parkr** [comment]
Hi! You can now add MathJax by copying [`_includes/head-custom.html`](https://github.com/pages-themes/minimal/blob/master/_includes/head-custom.html) into your site at `_includes/head-custom.html` and customizing it as you wish! This will all be added to the `<head>` tag.
