### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by omerayyildiz** [pages-themes/minimal#88]
How can I add google analytics to my page? 

Although I added an analytics.html file into the _includes folder and linked it to the config.yml file but google could not pull any data.

my page: https://omerayyildiz.com/nishgt
my repository: https://github.com/omerayyildiz/nishgt

**Comment by pedrominicz** [comment]
You can add by setting `site.google_analytics` in `_config.yml`.

**Comment by omerayyildiz** [comment]
i did that but it didn't work
![image](https://user-images.githubusercontent.com/34156233/96905273-e9840b80-14a0-11eb-9335-61eee8cc0596.png)
![image](https://user-images.githubusercontent.com/34156233/96905303-f30d7380-14a0-11eb-9a42-aaca388ed37a.png)

**Comment by pedrominicz** [comment]
`site.` is implicit in `_config.yml`. Change your `_config.yml` as follows:
```
logo: /assets/img/banner.jpg
theme: jekyll-theme-minimal
google_analytics: G-TPCXXYC26M
```

**Comment by omerayyildiz** [comment]
Not working :/
![image](https://user-images.githubusercontent.com/34156233/96911009-f3aa0800-14a8-11eb-9a18-f81e49a868d9.png)

**Comment by mmvanheusden** [comment]
The problem is caused by Google Analytics 4

**Comment by omerayyildiz** [comment]
What's problem in Google Analytics 4?

**Comment by ChristopherBull** [comment]
I am experiencing this issue too. When you create a new account/property in Google Analytics, it defaults to Google Analytics 4 which (as I understand it) is not backwards compatible with previous collection JS files from before Nov 2020.

The problem (and solutions) with Google Analytics 4 in Jekyll themes are summarised in other similar repositories, e.g.:

- https://github.com/jekyll/minima/issues/555
- https://github.com/jekyll/minima/issues/561

**Comment by mosaicgeospatial** [comment]
For anyone else having this problem, here is how I solved it.
Add your google analytics tag to _config.yaml as stated previously:
`google_analytics: G-XXXXXXXXXX`

Make your own _layouts/default.html file - copy the contents from the same file in the minimal repository:
[https://github.com/pages-themes/minimal/blob/master/_layouts/default.html](https://github.com/pages-themes/minimal/blob/master/_layouts/default.html)

Find the following section at the bottom of the file:
```
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', '{{ site.google_analytics }}', 'auto');
      ga('send', 'pageview');
    </script>
```
Replace it with this:
```
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '{{ site.google_analytics }}');
    </script>
```

**Comment by mmvanheusden** [comment]
@mosaicgeospatial Could you open a pull request for this?

**Comment by pedrominicz** [comment]
I created a pull request with @mosaicgeospatial's changes. Also, @omerayyildiz, please keep the issue opened until it has been fully resolved.
