### ISSUE TITLE
Allow for hiding the "View the Project on GitHub" button

### ISSUE THREAD

**Issue by zachsa** [pages-themes/minimal#90]
Hi,

I'm using this theme for a private repo, and would like to disable the "View the Project on GitHub" button. Is there a way to do this?

**Comment by MatBenfield** [comment]
@zachsa have a look at this section of the help https://github.com/pages-themes/minimal#layouts if you make your own copy of the template, you add some variables to the config and do some if statements to show/hide

**Comment by zachsa** [comment]
Thanks for the reply! I saw in the docs that you can pass custom scss, and I was able to hide stuff that way.
