### ISSUE TITLE
How can add links to the bar on the side.

### ISSUE THREAD

**Issue by ArnavMotwani** [pages-themes/minimal#91]
I am using the minimal them in a couple simple repos. I want to add links to each page on the side of the page (above the "View the project on GitHub" button but below the logo. How can I do this?

**Comment by MatBenfield** [comment]
You should be able to do this by using the template file see the notes below

https://github.com/pages-themes/minimal#layouts

**Comment by glowkeeper** [comment]
Yeah, but how? I can see how to create direct links, but I'd like to create a navigation menu, say `menu.md`, then do something like `{{ menu }}` in the header section. Is something like that possible?

**Comment by godalming123** [comment]
yes it is create a html file in _includes folder fo whatever you want to put in the header then in _layouts edit deafualt.html file and in the body tag paste `{% include name_of_file.html %}`

**Comment by BDHU** [comment]
Something like [this](https://www.bodunhu.com/)? FYI, the code is [here](https://github.com/BDHU/bdhu.github.io/blob/master/_layouts/default.html#L50). Feel free to use the modified [theme](https://github.com/BDHU/minimalist)

**Comment by solvaholic** [comment]
Oh I like that @BDHU !

> Yeah, but how?

@glowkeeper I think you're asking about step 5 in [the instructions @MatBenfield linked](https://github.com/pages-themes/minimal/tree/814b8723af0aa0ada9b5784da6b73d862bb74150#layouts).

> I can see how to create direct links, but I'd like to create a navigation menu, say `menu.md`, then do something like `{{ menu }}` in the header section. Is something like that possible?

Yes. If you put `menu.md` in your site's `_includes` directory then you can include it the same way `_layouts/default.html` includes `_includes/head-custom.html`:

https://github.com/pages-themes/minimal/blob/814b8723af0aa0ada9b5784da6b73d862bb74150/_layouts/default.html#L13

Those `{% %}` are for Jekyll to process when `jekyll build` runs. Jekyll's [_Includes_ documentation](https://jekyllrb.com/docs/includes/) says more about that `include` tag.

Be sure to consider where (and whether) you wish your menu to appear on narrower displays. @BDHU's example works very well; Compare it to the default contents in this repository, to see how it's been modified.

**Comment by solvaholic** [comment]
> Yeah, but how? I can see how to create direct links, but I'd like to create a navigation menu, say `menu.md`, then do something like `{{ menu }}` in the header section. Is something like that possible?

@ArnavMotwani @glowkeeper in case it'll help, I set up a demo:

https://solvaholic.github.io/reimagined-fortnight/

The repository's commit history explains the steps I took:

https://github.com/solvaholic/reimagined-fortnight/commits/main

This weekend I set out to add dark mode to a Minimal-themed Pages site, and got so much more. https://github.com/BDHU/bdhu.github.io is fantastic! :bow:

**Comment by godalming123** [comment]
> > Yeah, but how? I can see how to create direct links, but I'd like to create a navigation menu, say `menu.md`, then do something like `{{ menu }}` in the header section. Is something like that possible?
> 
> @ArnavMotwani @glowkeeper in case it'll help, I set up a demo:
> 
> https://solvaholic.github.io/reimagined-fortnight/
> 
> The repository's commit history explains the steps I took:
> 
> https://github.com/solvaholic/reimagined-fortnight/commits/main
> 
> This weekend I set out to add dark mode to a Minimal-themed Pages site, and got so much more. https://github.com/BDHU/bdhu.github.io is fantastic! bow

did you use my fork for dark mode with a minimal theme (https://github.com/godalming123/minimal) ? Your first example has the exact same colors. If you did use my fork I'm amazed to see 2 people adopt it already!

**Comment by vaibhavvikas** [comment]
This feature should be merged into the main branch. This is one of the most important features if we require to create documentation. Let's say we want navigation on the page, we can simply add desired items on the sidebar, and the users can simply navigate.

**Comment by godalming123** [comment]
If you are going to use minimal I would recommend using [BDHU's fork](https://github.com/BDHU/minimalist) it's mostly the same but adds dark mode and is still maintained

**Comment by vaibhavvikas** [comment]
> If you are going to use minimal I would recommend using [BDHU's fork](https://github.com/BDHU/minimalist) it's mostly the same but adds dark mode and is still maintained

Thanks for the suggestion. I created my template based on minimal, using the minimalist theme by BDHU to add Navigation on the sidebar. 

https://vaibhavvikas.github.io/jekyll-theme-minimalistic/
