### ISSUE TITLE
Floating Footer covers content

### ISSUE THREAD

**Issue by innomadic** [pages-themes/minimal#93]
I am using the theme via GitHub pages and notice that the page footer is effectively floating on top of my page content - meaning that the text of my content and the footer are illegible.  

     
The footer is this:
"This page was generated by GitHub Pages. "

Is this the intended design?

**Comment by innomadic** [comment]
Sorry I think this was due to a template I had included.  Closing.

**Comment by dgreene1** [comment]
I've noticed that this occurs as well. I think it's just not noticeable until you do something that shrinks the vertical space like opening the chrome dev tools on the bottom.
