### ISSUE TITLE
.github/workflows/ci.yaml 

### ISSUE THREAD

**Issue by Jwmc999** [pages-themes/minimal#95]
Hi, 

I found an issue from ci.yaml as below:

Run script/bootstrap
/home/runner/work/_temp/63854597-b0cf-41b3-a7a5-dc2b0c4df45f.sh: line 1: script/bootstrap: Permission denied
Error: Process completed with exit code 126.

Any advice on how I can eliminate this error?

Thank you

**Comment by parkr** [comment]
Hi! It looks like this has been fixed – sorry about that!

https://github.com/pages-themes/minimal/actions

**Comment by reportMPIBI** [comment]
Hi, 

I see the same error occurring: 
/home/runner/work/_temp/e8f0d6a3-7d85-4cb1-af22-7705baea92a8.sh: line 1: script/bootstrap: Permission denied
Error: Process completed with exit code 126.

Any advice on how I can fix this? 

Thanks a lot
